apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-strimzi-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.9.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 1 # 개발 환경용 (프로덕션에서는 더 높게)
      transaction.state.log.replication.factor: 1 # 개발 환경용 (프로덕션에서는 더 높게)
      transaction.state.log.min.isr: 1 # 개발 환경용 (프로덕션에서는 더 높게)
      default.replication.factor: 1 # 개발 환경용 (프로덕션에서는 더 높게)
      min.insync.replicas: 1 # 개발 환경용 (프로덕션에서는 더 높게)
      log.level: "INFO"  # 전체 로그 레벨 설정
      # 특정 로거에 대한 세부 설정
      log4j.logger.org.apache.zookeeper: "WARN"
      log4j.logger.org.I0Itec.zkclient: "WARN"
      log4j.logger.org.apache.kafka: "INFO"
      log4j.logger.kafka: "INFO"
      log4j.logger.state.change.logger: "TRACE"
      log4j.logger.kafka.request.logger: "WARN"
      log.retention.hours: 168  # 7일간 로그 보존
      log.retention.bytes: 1073741824  # 1GB 이상 로그 보존하지 않음
      log.segment.bytes: 1073741824  # 로그 세그먼트 크기 1GB
      log.cleanup.policy: delete  # 오래된 로그 삭제
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi # 개발 환경용 (필요 시 확장 가능)
        deleteClaim: false 
        class: kafka-ebs-sc 
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim 
      size: 5Gi 
      deleteClaim: false 
      class: zookeeper-ebs-sc 
